### ISSUE TITLE
Upvote feature

### ISSUE THREAD

**Issue by lab596** [Polyratings/polyratings#103]
Is it possible for a user viewing a review to leave an upvote? This would enable users to sort reviews by reviews instead of date (this can be an option that users can toggle between).

**Comment by AddisonTustin** [comment]
I totally see the utility/helpfulness of this feature! But unfortunately this isn't something we can actually do because we don't really track users. We don't have a mechanism to basically distinguish between a person who upvotes, a bot who's spamming, someone who double votes, etc. without building a persistent (read: forever-ish) mechanism to actually associate actors with some identity.

**Comment by lab596** [comment]
Ah, I understand.
